version: '2.1'
services:

  elasticsearch: # Elasticsearch Instance
    container_name: gs-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: # Persist ES data in seperate "esdata" volume
      - ./app/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports: # Expose Elasticsearch ports
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    expose:
      - "9200"
      - "9300"

  web:
    build: .
    restart: on-failure
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "5000:5000"


